apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "wallet.labels" . | nindent 4 }}
type: Opaque
data:
  wallet_mongo_url: {{ .Values.walletMongoUrl | b64enc }}